// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Logic.Sms.Client.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class GetSmsResponse
    {
        /// <summary>
        /// Initializes a new instance of the GetSmsResponse class.
        /// </summary>
        public GetSmsResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the GetSmsResponse class.
        /// </summary>
        /// <param name="smsMessageId">A unique identifier for the SMS
        /// message.</param>
        /// <param name="status">Possible values include: 'Sending', 'Sent',
        /// 'Failed'</param>
        public GetSmsResponse(System.Guid smsMessageId, string status)
        {
            SmsMessageId = smsMessageId;
            Status = status;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets a unique identifier for the SMS message.
        /// </summary>
        [JsonProperty(PropertyName = "smsMessageId")]
        public System.Guid SmsMessageId { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Sending', 'Sent', 'Failed'
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        public string Status { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Status == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Status");
            }
        }
    }
}
