// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Logic.FileSecurity.Client.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ProviderConfigurationListItem
    {
        /// <summary>
        /// Initializes a new instance of the ProviderConfigurationListItem
        /// class.
        /// </summary>
        public ProviderConfigurationListItem()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ProviderConfigurationListItem
        /// class.
        /// </summary>
        /// <param name="providerConfigurationId">The unique ID of the provider
        /// configuration, which can be used to send SMS requests.</param>
        /// <param name="name">A user-provided display that describes the
        /// provider configuration.</param>
        /// <param name="description">Internal details of the provider
        /// configuration, which are suitable for being
        /// displayed in a list, and help the reader to identity the provider
        /// configuration
        /// at a glance.</param>
        /// <param name="type">The SMS gateway (SMS Provider) type display
        /// name. E.g. "Twilio" or "LinkMobility".</param>
        /// <param name="isApproved">The Status for Sms logic provider</param>
        public ProviderConfigurationListItem(System.Guid providerConfigurationId, string name, string description = default(string), string type = default(string), bool? isApproved = default(bool?))
        {
            ProviderConfigurationId = providerConfigurationId;
            Name = name;
            Description = description;
            Type = type;
            IsApproved = isApproved;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the unique ID of the provider configuration, which can
        /// be used to send SMS requests.
        /// </summary>
        [JsonProperty(PropertyName = "providerConfigurationId")]
        public System.Guid ProviderConfigurationId { get; set; }

        /// <summary>
        /// Gets or sets a user-provided display that describes the provider
        /// configuration.
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets internal details of the provider configuration, which
        /// are suitable for being
        /// displayed in a list, and help the reader to identity the provider
        /// configuration
        /// at a glance.
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// Gets or sets the SMS gateway (SMS Provider) type display name. E.g.
        /// "Twilio" or "LinkMobility".
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

        /// <summary>
        /// Gets or sets the Status for Sms logic provider
        /// </summary>
        [JsonProperty(PropertyName = "isApproved")]
        public bool? IsApproved { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Name == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Name");
            }
        }
    }
}
