// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Logic.Sms.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SendBulkSmsResponse
    {
        /// <summary>
        /// Initializes a new instance of the SendBulkSmsResponse class.
        /// </summary>
        public SendBulkSmsResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SendBulkSmsResponse class.
        /// </summary>
        /// <param name="smsMessageId">A unique identifier for the SMS
        /// message.</param>
        /// <param name="toPhoneNumber">Recipient phone number</param>
        public SendBulkSmsResponse(System.Guid? smsMessageId = default(System.Guid?), string toPhoneNumber = default(string))
        {
            SmsMessageId = smsMessageId;
            ToPhoneNumber = toPhoneNumber;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets a unique identifier for the SMS message.
        /// </summary>
        [JsonProperty(PropertyName = "smsMessageId")]
        public System.Guid? SmsMessageId { get; set; }

        /// <summary>
        /// Gets or sets recipient phone number
        /// </summary>
        [JsonProperty(PropertyName = "toPhoneNumber")]
        public string ToPhoneNumber { get; set; }

    }
}
