# The default generator of autorest was updated by autorest --csharp to the new version V3 , which uses @autorest/csharp package and it will have few side effects
# It will generate code based on the .NET SDK guidelines, which will be totally different than the code generated by V2 version.
# The dotnet core runtime 3.1+ is required.
# If you still want to generate code based on V2 version, you can add --legacy flag to the command line to get the previous behavior
# Refer to the link - https://github.com/Azure/autorest.csharp

 autorest --input-file=swagger-v2.json --output-folder=. --namespace=Kmd.Logic.FileSecurity.Client --csharp --legacy --override-client-name=InternalClient --add-credentials

(Get-Content "InternalClient.cs") |
	Foreach-Object {$_ -replace 'public partial class InternalClient', 'internal partial class InternalClient'} | 
	Set-Content "InternalClient.cs"

(Get-Content "IInternalClient.cs") | 
	Foreach-Object {$_ -replace 'public partial interface IInternalClient', 'internal partial interface IInternalClient'} |
	Set-Content "IInternalClient.cs"

(Get-Content "InternalClientExtensions.cs") | 
	Foreach-Object {$_ -replace 'public static partial class InternalClientExtensions', 'internal static partial class InternalClientExtensions'} |
	Set-Content "InternalClientExtensions.cs"
