// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Logic.Sms.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class LogicProviderConfig
    {
        /// <summary>
        /// Initializes a new instance of the LogicProviderConfig class.
        /// </summary>
        public LogicProviderConfig()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the LogicProviderConfig class.
        /// </summary>
        public LogicProviderConfig(string description = default(string), bool? isApproved = default(bool?), ServiceWindow smsServiceWindow = default(ServiceWindow))
        {
            Description = description;
            IsApproved = isApproved;
            SmsServiceWindow = smsServiceWindow;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isApproved")]
        public bool? IsApproved { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "smsServiceWindow")]
        public ServiceWindow SmsServiceWindow { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (SmsServiceWindow != null)
            {
                SmsServiceWindow.Validate();
            }
        }
    }
}
