// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Logic.Api.Client.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ServiceWindowTime
    {
        /// <summary>
        /// Initializes a new instance of the ServiceWindowTime class.
        /// </summary>
        public ServiceWindowTime()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ServiceWindowTime class.
        /// </summary>
        public ServiceWindowTime(int hour, int minute)
        {
            Hour = hour;
            Minute = minute;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "hour")]
        public int Hour { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "minute")]
        public int Minute { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Hour > 23)
            {
                throw new ValidationException(ValidationRules.InclusiveMaximum, "Hour", 23);
            }
            if (Hour < 0)
            {
                throw new ValidationException(ValidationRules.InclusiveMinimum, "Hour", 0);
            }
            if (Minute > 59)
            {
                throw new ValidationException(ValidationRules.InclusiveMaximum, "Minute", 59);
            }
            if (Minute < 0)
            {
                throw new ValidationException(ValidationRules.InclusiveMinimum, "Minute", 0);
            }
        }
    }
}
